-- Oracle Database Setup Script for Software Development Document Environment
-- Run this script to initialize the tables, sequences, and initial configurations.

-- Drop existing tables (if any)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE app_audit_logs CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE app_documents CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE app_users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE app_configs CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Create Users table
CREATE TABLE app_users (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) DEFAULT 'MAKER' NOT NULL, -- ADMIN, MAKER, CHECKER
    is_locked CHAR(1) DEFAULT 'N' NOT NULL, -- 'Y' or 'N'
    pwd_reset_token VARCHAR2(100),
    pwd_expiry_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create Documents table
CREATE TABLE app_documents (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id_code VARCHAR2(30) UNIQUE NOT NULL, -- auto sequence e.g., SDE-P101, SDE-P201, SDE-P202
    app_code VARCHAR2(3) NOT NULL,
    phase_number NUMBER(2) NOT NULL, -- 1 to 7
    document_title VARCHAR2(150) NOT NULL, --deliverable title e.g. Business Case / Functional Specification
    description VARCHAR2(500) NOT NULL, -- configurable description
    version_number VARCHAR2(20) NOT NULL,
    document_code VARCHAR2(50) NOT NULL,
    file_path VARCHAR2(500),
    file_name VARCHAR2(250),
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PENDING, APPROVED, REJECTED, PROCESSED
    maker_username VARCHAR2(50) NOT NULL,
    checker_username VARCHAR2(50),
    checker_remarks VARCHAR2(500),
    processed_status VARCHAR2(50) DEFAULT 'NOT PROCESSED' NOT NULL, -- PROCESSED, NOT PROCESSED
    recommendations CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create Audit Logs table
CREATE TABLE app_audit_logs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR2(100) NOT NULL, -- UPLOAD, APPROVAL, REJECTION, USER_LOCK, USER_UNLOCK, PW_RESET
    doc_id_code VARCHAR2(30),
    performed_by VARCHAR2(50) NOT NULL,
    details VARCHAR2(1000),
    log_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create System Configs table
CREATE TABLE app_configs (
    config_key VARCHAR2(100) PRIMARY KEY,
    config_value VARCHAR2(1000) NOT NULL
);

-- Seed Data
INSERT INTO app_users (username, password, role, is_locked, pwd_expiry_date)
VALUES ('admin', '$2a$10$8.UnVuG9HHgffUDAlk8GPuK1v5I4.u6H0I8.I8xXm16a6K78I0U7m', 'ADMIN', 'N', SYSDATE + 90); -- password is 'admin123'

INSERT INTO app_users (username, password, role, is_locked, pwd_expiry_date)
VALUES ('maker', '$2a$10$8.UnVuG9HHgffUDAlk8GPuK1v5I4.u6H0I8.I8xXm16a6K78I0U7m', 'MAKER', 'N', SYSDATE + 90); -- password is 'admin123'

INSERT INTO app_users (username, password, role, is_locked, pwd_expiry_date)
VALUES ('checker', '$2a$10$8.UnVuG9HHgffUDAlk8GPuK1v5I4.u6H0I8.I8xXm16a6K78I0U7m', 'CHECKER', 'N', SYSDATE + 90); -- password is 'admin123'

INSERT INTO app_configs (config_key, config_value) VALUES ('APP_NAME', 'Software Development Document Environment');
INSERT INTO app_configs (config_key, config_value) VALUES ('DEFAULT_APP_CODE', 'SDE');
INSERT INTO app_configs (config_key, config_value) VALUES ('POLLING_DIR', './polling_folder');
INSERT INTO app_configs (config_key, config_value) VALUES ('ENABLE_SMS_AUTH_SIGNUP', 'false');
INSERT INTO app_configs (config_key, config_value) VALUES ('ENABLE_EMAIL_AUTH_SIGNUP', 'false');
INSERT INTO app_configs (config_key, config_value) VALUES ('ENABLE_APPROVER_SMS_NOTIFY', 'false');
INSERT INTO app_configs (config_key, config_value) VALUES ('ENABLE_APPROVER_EMAIL_NOTIFY', 'false');

COMMIT;
