# Server Port Configuration
server.port=8080

# Profiles Active
spring.profiles.active=local

# Multipart File upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Log Configurations
logging.level.com.cth.sdm=DEBUG
